language: node_js
node_js:
  - "node"
  - "10"
  - "8"
  - "6"

cache: yarn
install: cd packages && yarn

script: yarn test

before_deploy: cd packages
deploy:
  # Deploy new version of eslint-config-eventbrite-legacy (but only on the "node" test matrix)
  - provider: script
    script: npx travis-deploy-once "yarn workspace eslint-config-eventbrite-legacy publish"
    on:
      tags: true
      condition: TRAVIS_TAG =~ ^eslint-config-eventbrite-legacy-v.*$

  # Deploy new version of eslint-config-eventbrite (but only on the "node" test matrix)
  - provider: script
    script: npx travis-deploy-once "yarn workspace eslint-config-eventbrite publish"
    on:
      tags: true
      condition: TRAVIS_TAG =~ ^eslint-config-eventbrite-v.*$

  # Deploy new version of eslint-config-eventbrite-react (but only on the "node" test matrix)
  - provider: script
    script: npx travis-deploy-once "yarn workspace eslint-config-eventbrite-react publish"
    on:
      tags: true
      condition: TRAVIS_TAG =~ ^eslint-config-eventbrite-react-v.*$
